"""empty message

Revision ID: 8a6207801331
Revises: df29ed3acc9b
Create Date: 2017-11-18 18:05:53.781242

"""

# revision identifiers, used by Alembic.
revision = '8a6207801331'
down_revision = 'df29ed3acc9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('published_on', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['User.id'], ),
    sa.ForeignKeyConstraint(['topic'], ['Topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('added_on', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['publication'], ['Publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('name', name='user_name_key')
    )
    op.drop_table('Comment')
    op.drop_table('Publication')
    op.drop_table('User')
    op.drop_table('Topic')
    # ### end Alembic commands ###
